<?php

use Api\TaskApi\Router;
use Api\TaskApi\Task;
use Config\Database;

require_once "./vendor/autoload.php";
header("Content-Type: application/json");

//Database Initialization
$db = new Database();
$conn = $db->getConnection();
$task = new Task($conn);
$router = new Router($task);

//Handle Request
$router->handleRequest();

$conn->close();
<?php

// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, $err);
        } elseif (!headers_sent()) {
            echo $err;
        }
    }
    trigger_error(
        $err,
        E_USER_ERROR
    );
}

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit7338457a5c777c165504495c2e0ffe04::getLoader();


?>